openapi: 3.0.3
info:
  title: Village Storefront API
  version: 1.0.0
  description: REST API for Village Storefront ecommerce platform

servers:
  - url: /api/v1

paths:
  /health:
    get:
      operationId: healthCheck
      summary: Health check endpoint
      tags: [System]
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          example: "ok"
