apiVersion: apps/v1
kind: Deployment
metadata:
  name: village-storefront-workers
spec:
  template:
    spec:
      containers:
      - name: worker
        env:
        # Override log level for staging
        - name: QUARKUS_LOG_LEVEL
          value: "DEBUG"
        # Reduced queue capacities for staging
        - name: JOBS_QUEUE_CAPACITY_CRITICAL
          value: "500"
        - name: JOBS_QUEUE_CAPACITY_HIGH
          value: "2000"
        - name: JOBS_QUEUE_CAPACITY_DEFAULT
          value: "5000"
