---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: village-storefront

resources:
  - otel-collector-deployment.yaml
  - otel-collector-configmap.yaml

commonLabels:
  app: village-storefront
  component: observability
