package villagecompute.storefront.security;

import java.net.URI;
import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RFC 7807 Problem Details for HTTP APIs.
 *
 * <p>
 * Standardized error response format for REST APIs. Used for rate limiting (429), authentication (401), authorization
 * (403), and other error conditions.
 *
 * <p>
 * <strong>Example Usage:</strong>
 *
 * <pre>
 * ProblemDetail problem = ProblemDetail.forStatus(429).withTitle("Too Many Requests")
 *         .withDetail("Rate limit exceeded. Please retry after 42 seconds.").build();
 * return Response.status(429).entity(problem).build();
 * </pre>
 *
 * <p>
 * References:
 * <ul>
 * <li>RFC 7807: https://tools.ietf.org/html/rfc7807</li>
 * <li>RFC 6585: https://tools.ietf.org/html/rfc6585 (429 Too Many Requests)</li>
 * <li>Task I6.T2: Security hardening - RFC 7807 Problem Details for rate limiting</li>
 * </ul>
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ProblemDetail {

    /**
     * A URI reference (RFC3986) that identifies the problem type.
     *
     * <p>
     * When dereferenced, it should provide human-readable documentation. If not set, defaults to "about:blank".
     */
    @JsonProperty("type")
    private URI type;

    /**
     * A short, human-readable summary of the problem type.
     *
     * <p>
     * Should not change from occurrence to occurrence of the problem (e.g., "Unauthorized", "Too Many Requests").
     */
    @JsonProperty("title")
    private String title;

    /**
     * The HTTP status code generated by the origin server for this occurrence.
     */
    @JsonProperty("status")
    private Integer status;

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     *
     * <p>
     * Should focus on helping the client correct the issue (e.g., "Rate limit exceeded. Please retry after 42
     * seconds.").
     */
    @JsonProperty("detail")
    private String detail;

    /**
     * A URI reference that identifies the specific occurrence of the problem.
     *
     * <p>
     * Can be used to link to logs, support tickets, or other resources.
     */
    @JsonProperty("instance")
    private URI instance;

    /**
     * Extension members for additional context (e.g., validation errors, trace IDs).
     */
    private Map<String, Object> extensions;

    /**
     * Default constructor for JSON deserialization.
     */
    public ProblemDetail() {
        this.type = URI.create("about:blank");
        this.extensions = new HashMap<>();
    }

    /**
     * Create a ProblemDetail builder for a specific HTTP status code.
     *
     * @param status
     *            HTTP status code
     * @return builder instance
     */
    public static Builder forStatus(int status) {
        return new Builder().withStatus(status);
    }

    /**
     * Create a ProblemDetail for 401 Unauthorized.
     *
     * @param detail
     *            specific error message
     * @return ProblemDetail instance
     */
    public static ProblemDetail unauthorized(String detail) {
        return forStatus(401).withTitle("Unauthorized").withDetail(detail).build();
    }

    /**
     * Create a ProblemDetail for 403 Forbidden.
     *
     * @param detail
     *            specific error message
     * @return ProblemDetail instance
     */
    public static ProblemDetail forbidden(String detail) {
        return forStatus(403).withTitle("Forbidden").withDetail(detail).build();
    }

    /**
     * Create a ProblemDetail for 429 Too Many Requests.
     *
     * @param detail
     *            specific error message
     * @return ProblemDetail instance
     */
    public static ProblemDetail tooManyRequests(String detail) {
        return forStatus(429).withTitle("Too Many Requests").withDetail(detail).build();
    }

    // Getters and setters

    public URI getType() {
        return type;
    }

    public void setType(URI type) {
        this.type = type;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    public URI getInstance() {
        return instance;
    }

    public void setInstance(URI instance) {
        this.instance = instance;
    }

    public Map<String, Object> getExtensions() {
        return extensions;
    }

    public void setExtensions(Map<String, Object> extensions) {
        this.extensions = extensions;
    }

    /**
     * Add extension property.
     *
     * @param key
     *            property name
     * @param value
     *            property value
     */
    public void addExtension(String key, Object value) {
        this.extensions.put(key, value);
    }

    /**
     * Builder for ProblemDetail instances.
     */
    public static class Builder {
        private final ProblemDetail problem;

        public Builder() {
            this.problem = new ProblemDetail();
        }

        public Builder withType(URI type) {
            problem.type = type;
            return this;
        }

        public Builder withType(String type) {
            problem.type = URI.create(type);
            return this;
        }

        public Builder withTitle(String title) {
            problem.title = title;
            return this;
        }

        public Builder withStatus(int status) {
            problem.status = status;
            return this;
        }

        public Builder withDetail(String detail) {
            problem.detail = detail;
            return this;
        }

        public Builder withInstance(URI instance) {
            problem.instance = instance;
            return this;
        }

        public Builder withInstance(String instance) {
            problem.instance = URI.create(instance);
            return this;
        }

        public Builder withExtension(String key, Object value) {
            problem.extensions.put(key, value);
            return this;
        }

        public ProblemDetail build() {
            return problem;
        }
    }
}
