package villagecompute.storefront.jobs;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Observes;

import org.jboss.logging.Logger;

import villagecompute.storefront.tenant.CustomDomainVerified;

import io.quarkus.runtime.configuration.ConfigUtils;

/**
 * CDI observer that listens for CustomDomainVerified events and triggers SSL certificate provisioning.
 *
 * <p>
 * When a custom domain passes DNS verification, this handler is responsible for:
 * <ol>
 * <li>Generating a Kubernetes Certificate CRD manifest for the verified domain</li>
 * <li>Applying the manifest via kubectl (or Kubernetes Java API in production)</li>
 * <li>cert-manager automatically provisions Let's Encrypt certificate via ACME DNS-01 challenge</li>
 * <li>Certificate status is updated in CustomDomain.certificateExpiry by a separate monitoring job</li>
 * </ol>
 *
 * <p>
 * <strong>Development vs Production Behavior:</strong>
 * <ul>
 * <li><strong>Development:</strong> Logs certificate YAML to console (no actual K8s API calls)</li>
 * <li><strong>Production:</strong> Applies Certificate CRD via Kubernetes API client (requires RBAC)</li>
 * </ul>
 *
 * <p>
 * <strong>Kubernetes Resources Created:</strong>
 * <ul>
 * <li>Certificate CRD (cert-manager.io/v1) named after the domain</li>
 * <li>Ingress rule mapping custom domain to village-storefront service</li>
 * <li>TLS secret generated by cert-manager (referenced in Ingress)</li>
 * </ul>
 *
 * <p>
 * References:
 * <ul>
 * <li>Task I5.T4: Custom Domain SSL Automation</li>
 * <li>Runbook: docs/operations/runbook.md (Certificate Management)</li>
 * <li>cert-manager docs: https://cert-manager.io/docs/</li>
 * <li>Kubernetes Certificate API: https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.Certificate</li>
 * </ul>
 */
@ApplicationScoped
public class CertificateEventHandler {

    private static final Logger LOG = Logger.getLogger(CertificateEventHandler.class);

    // Namespace for Kubernetes resources (configurable via application.properties)
    private static final String K8S_NAMESPACE = ConfigUtils.getProfiles().contains("prod") ? "storefront"
            : "storefront-dev";

    // cert-manager ClusterIssuer name (defined in infra/kustomize/base/cert-manager/issuer.yaml)
    private static final String CERT_ISSUER_NAME = "letsencrypt-prod";

    /**
     * Handle CustomDomainVerified event by provisioning SSL certificate.
     *
     * <p>
     * This method is invoked asynchronously when DomainValidationJob fires a CustomDomainVerified event. It generates a
     * Kubernetes Certificate manifest and applies it to the cluster.
     *
     * @param event
     *            domain verified event containing CustomDomain entity
     */
    public void onDomainVerified(@Observes CustomDomainVerified event) {
        String domain = event.customDomain().domain;
        LOG.infof("Received CustomDomainVerified event - tenantId=%s, domain=%s", event.customDomain().tenant.id,
                domain);

        try {
            String certificateYaml = generateCertificateManifest(domain);

            if (ConfigUtils.getProfiles().contains("prod")) {
                // Production: Apply manifest via Kubernetes API
                applyCertificateManifest(certificateYaml);
                LOG.infof("Applied Certificate CRD for domain %s", domain);
            } else {
                // Development: Log manifest to console (no K8s API calls)
                LOG.infof("Development mode: Certificate manifest for domain %s:\n%s", domain, certificateYaml);
                LOG.warn("Skipping Kubernetes API call in development mode. Deploy manually with kubectl.");
            }

        } catch (Exception e) {
            LOG.errorf(e, "Failed to provision certificate for domain %s (tenantId=%s)", domain,
                    event.customDomain().tenant.id);
            // Do not rethrow - failure should not halt the entire event processing pipeline
        }
    }

    /**
     * Generate Kubernetes Certificate CRD manifest for a custom domain.
     *
     * <p>
     * The generated manifest references the ClusterIssuer defined in infra/kustomize/base/cert-manager/issuer.yaml and
     * requests a Let's Encrypt certificate via ACME DNS-01 challenge.
     *
     * @param domain
     *            fully qualified domain name (e.g., shop.example.com)
     * @return YAML manifest string
     */
    private String generateCertificateManifest(String domain) {
        // Sanitize domain for Kubernetes resource name (replace dots with dashes)
        String resourceName = domain.replace(".", "-");
        String secretName = resourceName + "-tls";

        // Generate Certificate CRD YAML
        return String.format("""
                ---
                apiVersion: cert-manager.io/v1
                kind: Certificate
                metadata:
                  name: %s
                  namespace: %s
                  labels:
                    app: village-storefront
                    domain: %s
                spec:
                  secretName: %s
                  issuerRef:
                    name: %s
                    kind: ClusterIssuer
                    group: cert-manager.io
                  dnsNames:
                    - %s
                  duration: 2160h  # 90 days
                  renewBefore: 720h  # 30 days before expiry
                """, resourceName, K8S_NAMESPACE, domain, secretName, CERT_ISSUER_NAME, domain);
    }

    /**
     * Apply Certificate manifest to Kubernetes cluster.
     *
     * <p>
     * This method uses the Kubernetes Java API client (io.fabric8.kubernetes.client) to create the Certificate
     * resource. Requires appropriate RBAC permissions (see infra/kustomize/base/cert-manager/issuer.yaml for
     * ServiceAccount + ClusterRole).
     *
     * @param manifestYaml
     *            Certificate CRD YAML manifest
     * @throws Exception
     *             if Kubernetes API call fails
     */
    private void applyCertificateManifest(String manifestYaml) throws Exception {
        // TODO: Implement Kubernetes API client integration
        // Example:
        // KubernetesClient client = new DefaultKubernetesClient();
        // client.load(new ByteArrayInputStream(manifestYaml.getBytes())).createOrReplace();
        // client.close();
        //
        // For MVP, operators can apply manifests manually via kubectl:
        // kubectl apply -f - <<EOF
        // <manifestYaml>
        // EOF

        throw new UnsupportedOperationException(
                "Kubernetes API client not yet implemented. Apply manifest manually via kubectl.");
    }
}
