---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: village-storefront-dev-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
  - host: storefront.local.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: village-storefront-gateway
            port:
              number: 8080
  - host: "*.storefront.local.dev"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: village-storefront-gateway
            port:
              number: 8080
