#!/usr/bin/env bash
#
# stripe_tunnel.sh - Stripe CLI webhook tunnel for local development
#
# This script starts a Stripe CLI listener that forwards webhook events to your
# local development server. The webhook signing secret is automatically exported
# to .env for Quarkus to pick up.
#
# Prerequisites:
#   - Stripe CLI installed: https://stripe.com/docs/stripe-cli
#   - Authenticated: stripe login
#   - STRIPE_SECRET_KEY set in .env or environment
#
# Usage:
#   ./scripts/dev/stripe_tunnel.sh [options]
#
# Options:
#   -p, --port PORT        Local server port (default: 8080)
#   -h, --host HOST        Local server host (default: localhost)
#   -e, --endpoint PATH    Webhook endpoint path (default: /api/webhooks/payments/stripe)
#   --help                 Show this help message
#
# Environment Variables:
#   STRIPE_SECRET_KEY      Stripe API secret key (required)
#   STRIPE_FORWARD_URL     Override full forward URL
#   QUARKUS_HTTP_PORT      Quarkus HTTP port (used if -p not specified)
#
# Examples:
#   ./scripts/dev/stripe_tunnel.sh
#   ./scripts/dev/stripe_tunnel.sh -p 8081
#   ./scripts/dev/stripe_tunnel.sh -e /api/webhooks/stripe
#

set -euo pipefail

# Default configuration
DEFAULT_PORT="${QUARKUS_HTTP_PORT:-8080}"
DEFAULT_HOST="localhost"
DEFAULT_ENDPOINT="/api/webhooks/payments/stripe"

# Parse arguments
PORT="${DEFAULT_PORT}"
HOST="${DEFAULT_HOST}"
ENDPOINT="${DEFAULT_ENDPOINT}"

while [[ $# -gt 0 ]]; do
    case $1 in
        -p|--port)
            PORT="$2"
            shift 2
            ;;
        -h|--host)
            HOST="$2"
            shift 2
            ;;
        -e|--endpoint)
            ENDPOINT="$2"
            shift 2
            ;;
        --help)
            sed -n '2,/^$/p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *)
            echo "Error: Unknown option: $1" >&2
            echo "Run '$0 --help' for usage information." >&2
            exit 1
            ;;
    esac
done

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $*"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}

# Check if stripe CLI is installed
if ! command -v stripe &> /dev/null; then
    log_error "Stripe CLI not found. Install it from: https://stripe.com/docs/stripe-cli"
    exit 1
fi

# Check if authenticated
if ! stripe config --list &> /dev/null; then
    log_error "Stripe CLI not authenticated. Run: stripe login"
    exit 1
fi

# Construct forward URL
FORWARD_URL="${STRIPE_FORWARD_URL:-http://${HOST}:${PORT}${ENDPOINT}}"

log_info "Starting Stripe webhook tunnel..."
log_info "Forward URL: ${FORWARD_URL}"
log_info ""
log_info "Stripe CLI will listen for webhook events and forward them to your local server."
log_info "The webhook signing secret will be exported to .env automatically."
log_info ""
log_warn "Press Ctrl+C to stop the tunnel."
log_info ""

# Create .env.stripe-tunnel file for the webhook secret
ENV_FILE=".env.stripe-tunnel"
TEMP_ENV_FILE="${ENV_FILE}.tmp"

trap 'log_info "Stopping Stripe webhook tunnel..."; rm -f "${TEMP_ENV_FILE}"; exit 0' EXIT INT TERM

# Run stripe listen and capture the output
stripe listen --forward-to "${FORWARD_URL}" --print-secret 2>&1 | while IFS= read -r line; do
    echo "${line}"

    # Extract webhook signing secret from output
    if [[ "${line}" =~ whsec_[a-zA-Z0-9]+ ]]; then
        WEBHOOK_SECRET="${BASH_REMATCH[0]}"

        # Write to temporary env file
        cat > "${TEMP_ENV_FILE}" << EOF
# Auto-generated by stripe_tunnel.sh
# Webhook signing secret for local development
# DO NOT COMMIT THIS FILE
STRIPE_WEBHOOK_SIGNING_SECRET=${WEBHOOK_SECRET}
EOF

        # Atomically replace the env file
        mv "${TEMP_ENV_FILE}" "${ENV_FILE}"

        log_success "Webhook signing secret exported to ${ENV_FILE}"
        log_info "Add this to your Quarkus config:"
        log_info "  quarkus.stripe.webhook-signing-secret=\${STRIPE_WEBHOOK_SIGNING_SECRET}"
        log_info ""
        log_info "Or source the file in your shell:"
        log_info "  source ${ENV_FILE}"
        log_info ""
    fi

    # Highlight webhook events
    if [[ "${line}" =~ "evt_" ]]; then
        log_success "Webhook event received: ${line}"
    fi
done
